### ISSUE TITLE
Cannot run sample out of the box

### ISSUE THREAD

**Issue by akoranteng** [FreakyAli/Maui.FreakyControls#106]
### Basic Information

- Version with issue:  
- Last known good version:  
- IDE:  
- Platform Target Frameworks: 
  - Android:  
  - iOS:  
  - Dotnet:  
- Target Devices:
  -

**Comment by FreakyAli** [comment]
@akoranteng sorry what?

**Comment by FreakyAli** [comment]
@akoranteng Can you please explain?

**Comment by FreakyAli** [comment]
Closing this because of no response, please open this back if you want to respond!
