### ISSUE TITLE
FreakyTextInputLayout : background color is visible outside border

### ISSUE THREAD

**Issue by FrankVDL2471** [FreakyAli/Maui.FreakyControls#108]
### Description

When setting a background color and a bordercorner radius, the background color is visible in the corners outside the border.

### Expected Behavior

Make the area outside the border transparant

### Actual Behavior

Background is colored

### Basic information

Package Version : 0.4.9
OS : Android 12

### Screenshots

![image](https://github.com/FreakyAli/Maui.FreakyControls/assets/24573204/d1d0cb41-3a2a-48cc-bbc1-be7d69c5eb2b)

**Comment by FreakyAli** [comment]
Please add relevant code

**Comment by FrankVDL2471** [comment]
`public class SjwingEntry : FreakyTextInputLayout {

	public SjwingEntry() {
		this.BorderCornerRadius = 5;
		this.BorderStrokeThickness = 2;
		this.BorderStroke = Brush.DarkGray;
		this.BackgroundColor = Colors.White;
		this.TextColor = Colors.Black;
		this.FontFamily = "Default";
		this.FontSize = 16;
	}
}`

**Comment by FreakyAli** [comment]
I was going to release it today so you are in luck, I have made a pre-release v0.4.10-pre. Check if that fixes your bug, if not you can reopen this.

**Comment by FrankVDL2471** [comment]
Just testes with the pre-release, but the problem is still the same

![image](https://github.com/FreakyAli/Maui.FreakyControls/assets/24573204/d6f1c68d-7840-43e0-b4fd-2ce45c5ce8d9)

**Comment by FreakyAli** [comment]
There should be a property by the name of `ControlBackgroundColor` use that

**Comment by FrankVDL2471** [comment]
The ControlBackgroundColor does the trick

One remarkt, the ControlBackgroundColor and TextColor can't be set using a Style

`	<Style x:Key="Field" TargetType="freaky:FreakyTextInputLayout">
		<Setter Property="FontFamily" Value="Default" />
		<Setter Property="FontSize" Value="16" />
		<Setter Property="HorizontalTextAlignment" Value="Start" />
		<Setter Property="VerticalTextAlignment" Value="Center" />
		<Setter Property="ControlBackgroundColor " Value="{xct:AppThemeResource Color_Background_Frame}" />
		<Setter Property="TextColor" Value="{xct:AppThemeResource Color_ExtraDark}" />
	</Style>
`

the controlbackgroundcolor property throws the following error

__Error	XFC0001	Cannot resolve property "ControlBackgroundColor " on type "FreakyTextInputLayout (property missing or missing accessors)"__


The textcolor does not throw an error but is not applied

**Comment by FreakyAli** [comment]
Interesting, I'll see if I can do something about it later, for now I hope this is good enough

**Comment by FrankVDL2471** [comment]
Yes, I'll set the colors outside the style as a workaround
