### ISSUE TITLE
Help needed to run sample

### ISSUE THREAD

**Issue by novastream** [FreakyAli/Maui.FreakyControls#114]
### Description

So this is kind of this issue #106 but with some context :)

Simply just need some pointers on how the get the sample working. 

### Code

Sample code from help page

### Expected Behavior

Working controls

### Actual Behavior

So I've added the package by nugget and added builder.InitializeFreakyControls(); to my MauProgram.cs.
The app builds without any issues but when I try to add a control to my MainPage.xaml I get the following error (see attached image)
![image](https://github.com/FreakyAli/Maui.FreakyControls/assets/4106389/08313b24-f697-42f6-a25d-b5461dcacff9)

### Basic Information

- Version with issue:  0.4.10
- Last known good version:  n/a
- IDE:  Visual Studio 2022 (Windows)
- Platform Target Frameworks: 
  - Android: 5.0
  - Dotnet:  8
- Target Devices:
  -   n/a

### Screenshots

Please see above

### Reproduction Link

n/a

**Comment by FreakyAli** [comment]
Did you add the namespace?

```xml
xmlns:freakyControls="clr-namespace:Maui.FreakyControls;assembly=Maui.FreakyControls"
```

**Comment by novastream** [comment]
Thank you, worked like a charm and thank you for a great project!

**Comment by FreakyAli** [comment]
No worries happy it helped, I also have other interesting stuff you can find on my GitHub be sure to check it out, Flutter and .NET MAUI only for now, but i might expand later maybe, be sure to leave a star at whatever you like and follow me for updates on these projects 😄
