### ISSUE TITLE
Cancel Button and OnKeyboardClicked Events

### ISSUE THREAD

**Issue by DgkanatsiosMasoutis** [FreakyAli/Maui.FreakyControls#117]
Even if the buttons are visible and clickable there are no events for the CancelButton and the Keyboard.

**Comment by FreakyAli** [comment]
What control are we talking about here again??

**Comment by DgkanatsiosMasoutis** [comment]
Sorry i that i didn't mention it. The FreakyPinCodeControl. I saw that in the wiki describes an Event called Keyboard_Clicked, tried to find it in previous versions but doesn't exist.

**Comment by DgkanatsiosMasoutis** [comment]
It will be great to include those two events!

**Comment by FreakyAli** [comment]
>tried to find it in previous versions but doesn't exist.

What version are you on currently?

**Comment by DgkanatsiosMasoutis** [comment]
> > tried to find it in previous versions but doesn't exist.
> 
> What version are you on currently?

0.4.10

**Comment by FreakyAli** [comment]
I just checked the documentation and I have not mentioned any of these events, is this a feature request?

https://github.com/FreakyAli/Maui.FreakyControls/wiki/FreakyPinCodeControl

**Comment by DgkanatsiosMasoutis** [comment]
> I just checked the documentation and I have not mentioned any of these events, is this a feature request?
> 
> https://github.com/FreakyAli/Maui.FreakyControls/wiki/FreakyPinCodeControl

It is but also if you look at the remarks you mentioned **Use event handlers like Keyboard_Clicked to update the code value when virtual keyboard buttons are pressed.**. Unless you are not talking about that then it is my fault.

**Comment by FreakyAli** [comment]
That is actually an internal event that I forgot to mention, Anyway I can do this whenever I make the next release, also please in case of future bugs follow the bug template thanks!

**Comment by FreakyAli** [comment]
@DgkanatsiosMasoutis FYI your changes are in the PR, the next pre-release will be released this weekend 😄 

https://github.com/FreakyAli/Maui.FreakyControls/blob/377292e958b4fd977f1352db21df797dbdac9618/MAUI.FreakyControls/MAUI.FreakyControls/Shared/FreakyCodeView/FreakyPinCodeControl.xaml.cs#L10

**Comment by FreakyAli** [comment]
No there are 3 events, for the numbers, the cancel button and the backspace button, hope this helps

**Comment by DgkanatsiosMasoutis** [comment]
> No there are 3 events, for the numbers, the cancel button and the backspace button, hope this helps

It helps a lot! Many thanks!

**Comment by FreakyAli** [comment]
@DgkanatsiosMasoutis Checkout the latest release
