### ISSUE TITLE
[0.4.12-pre] SKCanvasView Compile error

### ISSUE THREAD

**Issue by sk1llsh0t** [FreakyAli/Maui.FreakyControls#126]
### Description
Maybe you are already aware of this issue but after updating to 0.4.12-pre, I am getting a couple compile errors on Android. Downgrading back to 0.4.11 fixes the issue.

![image](https://github.com/FreakyAli/Maui.FreakyControls/assets/8394807/a2baa0ea-29b5-489d-af82-4219ccb7f670)

### Expected Behavior
Successful compile

### Actual Behavior
Error is thrown at compile time

### Basic Information

- Version with issue:  0.4.12-pre
- Last known good version: 0.4.11
- IDE:  JetBrains Rider
- Platform Target Frameworks: 
  - Android: 34
  - Dotnet:  8.0.203
- Target Devices:
  -  Samsung XCover6 Pro

### Screenshots
See screenshot of errors in Description

**Comment by FreakyAli** [comment]
Make sure you have the latest version of Skiasharp, clean your bin and obj and restart VS, this is not an issue with the plugin but a issue on your machine

**Comment by sk1llsh0t** [comment]
My project doesn't use skiasharp so I shouldn't have to install that package. I'll see if deleting everything in bin/obj folders fix the issue. I'll let you know.

**Comment by FreakyAli** [comment]
Your project uses FreakyControls, hence it uses skiasharp indirectly, make sure you update it to the latest at times vs doesn't do it

**Comment by sk1llsh0t** [comment]
I shouldn't have to maintain dependencies of dependencies. Then I need to keep track to the right versions of implicit dependencies to use for all my dependencies. It should implicitly pull in the right dependencies based on what is referenced. I shouldn't have to explicitly add a package to my project i'm not using directly. It is a recipe for disaster.

**Comment by sk1llsh0t** [comment]
If freakycontrols requires the latest skiasharp control, it should be upgraded in the freakycontrols csproj file from 2.88.0 to 2.88.8 (if this is indeed the version that has the expect components)

**Comment by sk1llsh0t** [comment]
I found this article which is my exact issue.
https://github.com/dotnet/maui/issues/19645

The last post (https://github.com/dotnet/maui/issues/19645#issuecomment-2105355240) suggests adding the SkiaSharp.Views.Maui.Controls.Compatibility to avoid this issue. Maybe add it to the freakycontrols csproj file to help alleviate this issue.

**Comment by sk1llsh0t** [comment]
Based on the weighttracker project mentioned above, he did the following commits to fix the issue...

https://github.com/fdmomtaz/WeightTracker-DotNetMaui/commit/b0966709d7ada5f3111a912fe2c8e3b853537ad3
https://github.com/fdmomtaz/WeightTracker-DotNetMaui/commit/4d1e1ba5c96b348aa264ef90d75708d1bca938a6

If i have time, i'll fork your develop branch, add these changes and see if the problem goes away. I'll let you know if it works...

**Comment by FreakyAli** [comment]
>I shouldn't have to maintain dependencies of dependencies. Then I need to keep track of the right versions of implicit dependencies to use for all my dependencies. It should implicitly pull in the right dependencies based on what is referenced. I shouldn't have to explicitly add a package to my project I'm not using directly. It is a recipe for disaster.

As much as I agree there are times when this breaks and we have no control over this...
