### ISSUE TITLE
FreakySwitch does not have the default switch animation 

### ISSUE THREAD

**Issue by FreakyAli** [FreakyAli/Maui.FreakyControls#128]
### Description

Add a switch animation to FreakySwitch, similar to [this](https://cdn.dribbble.com/users/1146702/screenshots/16376816/media/55e12bc6613cf9d0666faa70dbfa231f.gif)

### Expected Behavior

Should animate when switching between states 

### Actual Behavior

No animation is performed by the control, it just changes its state.

### Platforms

Needs to be done for both Android and iOS

**Comment by cgar0775** [comment]
Hello Ali, please assign me this ask please
