### ISSUE TITLE
Platform view cannot be null

### ISSUE THREAD

**Issue by FrankVDL2471** [FreakyAli/Maui.FreakyControls#131]
I'm getting the exact same error as described in this GitHub issue on the latest version

https://github.com/dotnet/maui/issues/17165

I'm testing it using a simulator running VS code on a Mac

**Comment by FreakyAli** [comment]
What Maui Controls version are you on?

**Comment by FrankVDL2471** [comment]
0.4.12

**Comment by FreakyAli** [comment]
Microsoft.Maui.Controls version 8.0.40 is what you should have!

**Comment by FreakyAli** [comment]
@FrankVDL2471 any updates?

**Comment by FrankVDL2471** [comment]
I was using Maui.Controls version 8.0.40.
But couldn't wait so I removed the dependecy on FreakyControls

**Comment by FreakyAli** [comment]
@FrankVDL2471  I have had this issue in the past are you facing this same issue 

https://github.com/FreakyAli/Maui.FreakyControls/issues/76

**Comment by FreakyAli** [comment]
I have been trying for a while and cannot replicate this!!

**Comment by FreakyAli** [comment]
@FrankVDL2471 Any updates?
