### ISSUE TITLE
FreakyTextInputLayout setting default text breaks the title animation 

### ISSUE THREAD

**Issue by FreakyAli** [FreakyAli/Maui.FreakyControls#135]
### Description

Just set a default text to the TIL 

### Code

```
<FreakyTextInputLayout
Text= "Whatever"
Title="Title"
BorderType="Full"
/>
```
### Expected Behavior

The title should animate to the top of the entry

### Actual Behavior

It gets stuck in the middle.

### Basic Information

Version with issue: 0.4.12

**Comment by sk1llsh0t** [comment]
Testing your code example, everything looks right to me when i test on an android device. There shouldn't be any animation if the text is prepopulated. the entry should show "Whatever" and the floating label "Title" should be at the top automatically (no animation). 

Here's what i see when the page loads using the above code snippet:
![image](https://github.com/FreakyAli/Maui.FreakyControls/assets/8394807/61f29535-e790-48b5-891a-4998aeb37548)

This is what i'd expect based on default values

**Comment by FreakyAli** [comment]
@sk1llsh0t I will recheck this soon and update my code, it probably has to do with the wrong values there

**Comment by FreakyAli** [comment]
@sk1llsh0t For some weird reason, I am unable to reproduce this again, I will keep this open for the time being if I reproduce this, I guess this happened in Hot reload.
