### ISSUE TITLE
SkiaSharp needs to be updated due to a well documented Vulnerability

### ISSUE THREAD

**Issue by usefulBeeing** [FreakyAli/Maui.FreakyControls#140]
### Description

I'm getting the following error while testing the `<freakyControls:FreakyAutoCompleteView />` control:

> Exception thrown: 'Microsoft.Maui.Platform.HandlerNotFoundException' in Microsoft.Maui.dll
Handler not found for view Maui.FreakyControls.FreakyAutoCompleteView.

### Actual Behavior

I'm assuming this might have something to do with upgrading to the latest SkiaSharp version after learning about the existing [vulnerability](https://github.com/advisories/GHSA-j7hp-h8jx-5ppr) with older versions.

### Screenshots

<img width="746" alt="_freaky5" src="https://github.com/user-attachments/assets/06ab821d-1d6e-47db-a138-3aa99589c4d4">

<img width="364" alt="_freaky1" src="https://github.com/user-attachments/assets/1984dead-8e57-4d59-8eb7-ab6fb85c126e">

<img width="623" alt="_freaky2" src="https://github.com/user-attachments/assets/ea8ccc70-c621-433b-bdc5-75f2adc439b4">

<img width="269" alt="_freaky3" src="https://github.com/user-attachments/assets/e035c495-9511-4a98-aacb-974028a9b22f">

<img width="358" alt="_freaky4" src="https://github.com/user-attachments/assets/d778cdab-6bcd-4aaf-9415-81e6538b054e">

**Comment by FreakyAli** [comment]
Was this working with the older versions of SkiaSharp? 

Just FYI, the controls only support Android and iOS for the time being

**Comment by usefulBeeing** [comment]
Good points!

> Was this working with the older versions of SkiaSharp?

I uninstalled SkiaSharp completely. So this is not what triggers the issue with the `FreakyAutoCompleteView` control.

With that said, the `SkiaSharp` version that ships with the `NuGet package` needs to be updated to the latest stable regardless, due to the vulnerability mentioned earlier.

> Just FYI, the controls only support Android and iOS for the time being.

I tested using Android 14.0 Pixel 5 Emulator, and the app just freezes.

I also tested using the Windows Machine, then the `Handler not found` exception is thrown.

This exception appears to affect `FreakySignatureCanvasView` and `FreakySignaturePadView`, as well as `FreakyAutoCompleteView`.

FreakyAutoCompleteView appears to be the only control that causes the Android Emulator to freeze.

> Also if you're running Android or iOS, can you try the latest pre-release and see if that works.

I rolled back to 0.4.9, same results.

**Comment by FreakyAli** [comment]
I'll check this once I'm a bit free for now though you'll have to make do with the pre-release v5.0

**Comment by FreakyAli** [comment]
I'm actually a bit busy for the next couple of months so I cannot check this, if you could narrow the issue down I could fix it and try releasing, but for the time being I might not be able to help here!

**Comment by usefulBeeing** [comment]
> if you could narrow the issue down I could fix it and try releasing.

Since you're obviously busy, I will try to narrow this down.
Regarding other issues, I might break them down into separate posts for future reference; for when you have more time.

**To get down to the point**:

The current _freaky_ stable NuGet release recommends SkiaSharp  2.88.0 and above.
The pre-release v5.0 recommends SkiaSharp  2.88.3 and above.

Both 2.88.0 and 2.88.3 are marked as Vulnerable.

Secure SkiaSharp versions start at 2.88.6 and above.

If you plan on a quick emergency release, it should tackle this one issue in my opinion.

**Comment by FreakyAli** [comment]
Cool
