### ISSUE TITLE
Path error in project file

### ISSUE THREAD

**Issue by langhaoabcd** [FreakyAli/Maui.FreakyControls#66]
Maui.FreakyControls.csproj
![image](https://github.com/FreakyAli/Maui.FreakyControls/assets/39892654/8ea241ad-be2e-46de-bce8-eb1c906e4951)

**Comment by FreakyAli** [comment]
Can you explain where you are facing this issue?

**Comment by FreakyAli** [comment]
I am able to build the master branch without any issues if you are facing problems do let me know and I can reopen this 

![image](https://github.com/FreakyAli/Maui.FreakyControls/assets/31090457/3a41cd99-4f0c-4314-816f-23d61cbfddec)

**Comment by FreakyAli** [comment]
@langhaoabcd Hey i just tried to open this in Windows and I saw the issue you had mentioned, I have added a fix for this a couple days ago forgot to inform you, feel free to check things out now, Also feel free to raise issues if you see any in the future! Thanks for the support!
