### ISSUE TITLE
FreakyTextInputLayout causes crash when use delete button on iOS

### ISSUE THREAD

**Issue by MaxiManus** [FreakyAli/Maui.FreakyControls#77]
When using a FreakyEntry or FreakyTextInputLayout on iOS u can tap on the selected entry again or long press it to open a menu for copy paste and much more. if u select "delete" or also "pause", probably more aswell, then the app gets crashed.
It seems like u are using a special menu for this. using standard maui entry opens another menu with less actions.
I did not find a possibility to deactivate this menu and no hint where u add this menu in your code.

I really like the freaky inputs, but this makes it hard to use them.
I'm just using it simple as that. And everywhere I use it, it leads to a crash if I open the menu and select delete for example.

Error Message:
**ObjCRuntime.ObjCException:** 'Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[Maui_FreakyControls_Platforms_iOS_NativeControls_FreakyUITextfield delete:]: unrecognized selector sent to instance 0x112e79400

Usage:
<freakyControls:FreakyTextInputLayout Grid.Column="1" Text="{Binding DisplayName}" HorizontalOptions="Fill" VerticalOptions="Center"/>

I am using the latest stable version 0.4.4
On Android there is no problem, just on iOS

**Comment by FreakyAli** [comment]
@MaxiManus  I would appreciate it if you could share some relevant stack trace, I am planning to add a new control this weekend and make a pre-release if there is a quick-fix for your issue i could try and squeeze it in as well

**Comment by FreakyAli** [comment]
For the time being, if you don't want your Entry to have the option for copy-pasting have you tried setting `AllowCopyPaste="False"`

**Comment by FreakyAli** [comment]
@MaxiManus Keep an eye out for #78 it has the fix that you are looking for!

**Comment by MaxiManus** [comment]
Wow, that sounds good.
So setting AllowCopyPaste="False" did not help at all.

Did you also check for the many other entries that appear in this menu? like insert image or someting that looks like chinese?
Many also caused a crash and I'm not sure how useful they are.

Another thing is that these menus seem to be always in english, no matter which language i set to the app. Just the CFBundleDevelopmentRegion changes the language of the menu, but then it is always fixed aswell.


![Menu](https://github.com/FreakyAli/Maui.FreakyControls/assets/144225728/62bafd95-a6f3-4a1f-82d6-63b88ac95320)


I still added a stack trace:

2023-09-07 09:26:01.177 FlaktRemoteControl[424:7741] -[Maui_FreakyControls_Platforms_iOS_NativeControls_FreakyUITextfield delete:]: unrecognized selector sent to instance 0x104845c00

**ObjCRuntime.ObjCException:** 'Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[Maui_FreakyControls_Platforms_iOS_NativeControls_FreakyUITextfield delete:]: unrecognized selector sent to instance 0x104845c00
Native stack trace:
	0   CoreFoundation                      0x0000000196979e54 725E49F4-653B-39BF-9A7A-8A3250911ECB + 40532
	1   libobjc.A.dylib                     0x000000018fc438d8 objc_exception_throw + 60
	2   CoreFoundation                      0x0000000196aee82c 725E49F4-653B-39BF-9A7A-8A3250911ECB + 1566764
	3   UIKitCore                           0x0000000199899d18 59CBC9B5-30AE-396E-A269-A986640001BC + 13978904
	4   CoreFoundation                      0x000000019698fcf8 725E49F4-653B-39BF-9A7A-8A3250911ECB + 130296
	5   CoreFoundation                      0x00000001969f8330 _CF_forwarding_prep_0 + 96
	6   UIKitCore                           0x0000000199a07efc 59CBC9B5-30AE-396E-A269-A986640001BC + 15478524
	7   UIKitCore                           0x0000000199b69398 59CBC9B5-30AE-396E-A269-A986640001BC + 16925592
	8   UIKitCore                           0x00000001991f0694 59CBC9B5-30AE-396E-A269-A986640001BC + 6993556
	9   UIKitCore                           0x00000001994726f4 59CBC9B5-30AE-396E-A269-A986640001BC + 9623284
	10  UIKitCore                           0x0000000199472160 59CBC9B5-30AE-396E-A269-A986640001BC + 9621856
	11  UIKitCore                           0x0000000198c03470 59CBC9B5-30AE-396E-A269-A986640001BC + 779376
	12  UIKitCore                           0x0000000198f710bc 59CBC9B5-30AE-396E-A269-A986640001BC + 4374716
	13  UIKitCore                           0x0000000198ceac30 59CBC9B5-30AE-396E-A269-A986640001BC + 1727536
	14  UIKitCore                           0x0000000198bcb60c 59CBC9B5-30AE-396E-A269-A986640001BC + 550412
	15  UIKitCore                           0x0000000198c77560 59CBC9B5-30AE-396E-A269-A986640001BC + 1254752
	16  UIKitCore                           0x00000001994fe93c 59CBC9B5-30AE-396E-A269-A986640001BC + 10197308
	17  UIKitCore                           0x0000000198c3c020 59CBC9B5-30AE-396E-A269-A986640001BC + 1011744
	18  UIKitCore                           0x0000000198c40978 59CBC9B5-30AE-396E-A269-A986640001BC + 1030520
	19  UIKitCore                           0x0000000198c3fc48 59CBC9B5-30AE-396E-A269-A986640001BC + 1027144
	20  UIKitCore                           0x0000000198c3f304 59CBC9B5-30AE-396E-A269-A986640001BC + 1024772
	21  UIKitCore                           0x0000000198c87018 59CBC9B5-30AE-396E-A269-A986640001BC + 1318936
	22  UIKitCore                           0x00000001998dfb28 59CBC9B5-30AE-396E-A269-A986640001BC + 14265128
	23  UIKitCore                           0x0000000199197498 59CBC9B5-30AE-396E-A269-A986640001BC + 6628504
	24  UIKitCore                           0x00000001997e3410 59CBC9B5-30AE-396E-A269-A986640001BC + 13231120
	25  UIKitCore                           0x00000001997e25dc 59CBC9B5-30AE-396E-A269-A986640001BC + 13227484
	26  CoreFoundation                      0x0000000196a45f34 725E49F4-653B-39BF-9A7A-8A3250911ECB + 876340
	27  CoreFoundation                      0x0000000196a5230c 725E49F4-653B-39BF-9A7A-8A3250911ECB + 926476
	28  CoreFoundation                      0x00000001969d61d0 725E49F4-653B-39BF-9A7A-8A3250911ECB + 418256
	29  CoreFoundation                      0x00000001969ebb8c 725E49F4-653B-39BF-9A7A-8A3250911ECB + 506764
	30  CoreFoundation                      0x00000001969f0ec0 CFRunLoopRunSpecific + 612
	31  GraphicsServices                    0x00000001d0a47368 GSEventRunModal + 164
	32  UIKitCore                           0x0000000198ee686c 59CBC9B5-30AE-396E-A269-A986640001BC + 3807340
	33  UIKitCore                           0x0000000198ee64d0 UIApplicationMain + 340
	34  FlaktRemoteControl                  0x0000000102d6c5f4 xamarin_UIApplicationMain + 60
	35  FlaktRemoteControl                  0x000000010308ddb8 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2367664
	36  FlaktRemoteControl                  0x000000010308cad8 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2362832
	37  FlaktRemoteControl                  0x00000001030824b4 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2320300
	38  FlaktRemoteControl                  0x0000000103080088 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2311040
	39  FlaktRemoteControl                  0x0000000103051090 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2118536
	40  FlaktRemoteControl                  0x0000000102fa0758 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1395280
	41  FlaktRemoteControl                  0x0000000102fa7000 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1422072
	42  FlaktRemoteControl                  0x000000010305628c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2139524
	43  FlaktRemoteControl                  0x0000000102d9900c xamarin_get_original_working_directory_path + 4368
	44  FlaktRemoteControl                  0x00000001030bc44c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2557764
	45  dyld                                0x00000001b5212960 7B63C573-6161-3B33-A3A2-9944BA59722F + 88416

**Comment by FreakyAli** [comment]
@MaxiManus Can you do something if you don't mind, Can you clone that branch, run it, check the changes and how are they affecting things, and then give me your feedback?

**Comment by MaxiManus** [comment]
I testet it and it now shows a useful and working menu. So your code seems fine. Thank you very much.

The only thing is now that it is in english although i set Thread.CurrentThread.CurrentCulture = "de" and Thread.CurrentThread.CurrentUICulture = "de"; But that is the same for standard entry menu in MAUI. So your code seems fine. But do you have any idea why it is using the wrong language there. the only way for me to change it would be setting CFBundleDevelopmentRegion  in infi.plist. but then it would be always "de". On android correct language is used.

**Comment by FreakyAli** [comment]
0.4.5-pre is now out!

**Comment by FreakyAli** [comment]
@MaxiManus  I did some research seems to me that when we change the Culture of the application in XF or Maui its not make any changes to the native cultures of iOS, I am not sure if this is a bug or its intended this way but that's what happens you can test the same by checking native iOS culture at runtime, it stays the same.
